---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - git
    - libxml2-dev
    - libxslt1-dev
    - make
    - nodejs-legacy
    - npm
    - python-dev
    - python3-dev
    - python-virtualenv
    - virtualenvwrapper
    - zlib1g-dev
  environment:
    LC_ALL: en_US.UTF-8

- name: install pip requirements
  pip: requirements=/vagrant/requirements.txt virtualenv=/vagrant/venv

- name: install pip development requirements
  pip: requirements=/vagrant/requirements-dev.txt virtualenv=/vagrant/venv

- name: install jshint
  npm: name=jshint global=yes state=latest

- name: hide login message
  file: path=/home/vagrant/.hushlogin
        owner=vagrant
        group=vagrant
        mode=0644
        state=touch

- name: install bash_profile
  template: src=dot.bash_profile.j2
            dest=/home/vagrant/.bash_profile
            owner=vagrant
            group=vagrant
            mode=0644
