---
- name: set timezone
  command: timedatectl set-timezone {{ ntp.timezone }}
  changed_when: false

- name: install ntp
  apt: pkg=ntp state=latest
  when: ntp.install_service

- name: make sure ntp is running
  service: name=ntp state=started enabled=yes
  when: ntp.install_service
