---
- name: install nginx
  apt: pkg=nginx state=latest

- name: copy nginx site
  template: src=jarvis2.j2
            dest=/etc/nginx/sites-available/jarvis2
            owner=root
            group=root
            mode=0644
  notify:
    - restart nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/jarvis2
        dest=/etc/nginx/sites-enabled/jarvis2
        owner=root
        group=root
        state=link

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  notify:
    - restart nginx

- name: make sure nginx is running
  service: name=nginx state=started enabled=yes
