---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: copy app config
  template: src=jarvis2.ini.j2
            dest=/etc/uwsgi/apps-available/jarvis2.ini
            owner=root
            group=root
            mode=0644
  notify:
    - restart uwsgi

- name: enable app config
  file: src=/etc/uwsgi/apps-available/jarvis2.ini
        dest=/etc/uwsgi/apps-enabled/jarvis2.ini
        owner=root
        group=root
        state=link
  notify:
    - restart uwsgi

- name: make sure uwsgi is running
  service: name=uwsgi state=started enabled=yes
